// Code generated by schema generator. DO NOT EDIT.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)



// Command - Shell command or binary name
type Command string




// ServiceUnit - Systemd unit name
type ServiceUnit string




// Version - Schema version in MAJOR.MINOR format
type Version string




// Metadata - 
type Metadata struct {
	Annotations map[string]interface{} `json:"annotations" yaml:"annotations"` // 
	Site string `json:"site" yaml:"site"` // Unique site identifier (typically hostname)
	Environment string `json:"environment" yaml:"environment"` // 
	Description string `json:"description" yaml:"description"` // 
	Labels map[string]interface{} `json:"labels" yaml:"labels"` // 
}




// EnvironmentEnum - 
type EnvironmentEnum string

const (
	EnvironmentEnumProduction EnvironmentEnum = "production"
	EnvironmentEnumStaging EnvironmentEnum = "staging"
	EnvironmentEnumDevelopment EnvironmentEnum = "development"
	EnvironmentEnumHomeLab EnvironmentEnum = "home-lab"
)




// Port - Valid TCP/UDP port number
type Port int




// Protocol - Network protocol
type Protocol string

const (
	ProtocolTcp Protocol = "tcp"
	ProtocolUdp Protocol = "udp"
	ProtocolIcmp Protocol = "icmp"
)




// ServiceState - Systemd service state
type ServiceState string

const (
	ServiceStateRunning ServiceState = "running"
	ServiceStateStopped ServiceState = "stopped"
	ServiceStateDisabled ServiceState = "disabled"
)




// UnixPath - Absolute Unix filesystem path
type UnixPath string




// NodeIdentity - 
type NodeIdentity struct {
	ContainerHost ContainerHostConfig `json:"container_host" yaml:"container_host"` // Configuration for container host role
	NetworkTuning NetworkTuning `json:"network_tuning" yaml:"network_tuning"` // Network-specific kernel parameters (semantic sysctl)
	SystemTuning SystemTuning `json:"system_tuning" yaml:"system_tuning"` // System-level kernel parameters (semantic sysctl)
	AccessControl AccessControl `json:"access_control" yaml:"access_control"` // Remote access and firewall configuration
	Version string `json:"version" yaml:"version"` // 
	Node NodeMetadata `json:"node" yaml:"node"` // 
	Roles []NodeRole `json:"roles" yaml:"roles"` // Roles this node performs (maps to actual workloads)
	VpnGateway VPNGatewayConfig `json:"vpn_gateway" yaml:"vpn_gateway"` // Configuration for VPN gateway role
}




// SystemTuning - System-level kernel parameters (semantic sysctl)
type SystemTuning struct {
	Swappiness int `json:"swappiness" yaml:"swappiness"` // VM swappiness (vm.swappiness)
	InotifyMaxUserWatches int `json:"inotify_max_user_watches" yaml:"inotify_max_user_watches"` // Maximum inotify watches (fs.inotify.max_user_watches)
	KernelPanic int `json:"kernel_panic" yaml:"kernel_panic"` // Seconds to wait before rebooting on panic
}




// AccessControl - Remote access and firewall configuration
type AccessControl struct {
	Ssh SSHConfig `json:"ssh" yaml:"ssh"` // 
	Firewall FirewallConfig `json:"firewall" yaml:"firewall"` // 
}




// FirewallConfig - 
type FirewallConfig struct {
	AllowedServices []string `json:"allowed_services" yaml:"allowed_services"` // Services to allow (ssh, http, https, openvpn, etc.)
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Provider FirewallProvider `json:"provider" yaml:"provider"` // 
	DefaultPolicy FirewallDefaultPolicy `json:"default_policy" yaml:"default_policy"` // 
}




// FirewallProvider - 
type FirewallProvider string

const (
	FirewallProviderUfw FirewallProvider = "ufw"
	FirewallProviderFirewalld FirewallProvider = "firewalld"
	FirewallProviderIptables FirewallProvider = "iptables"
)




// FirewallDefaultPolicy - 
type FirewallDefaultPolicy struct {
	Incoming string `json:"incoming" yaml:"incoming"` // 
	Outgoing string `json:"outgoing" yaml:"outgoing"` // 
}




// IncomingEnum - 
type IncomingEnum string

const (
	IncomingEnumAllow IncomingEnum = "allow"
	IncomingEnumDeny IncomingEnum = "deny"
	IncomingEnumReject IncomingEnum = "reject"
)




// OutgoingEnum - 
type OutgoingEnum string

const (
	OutgoingEnumAllow OutgoingEnum = "allow"
	OutgoingEnumDeny OutgoingEnum = "deny"
	OutgoingEnumReject OutgoingEnum = "reject"
)




// SSHConfig - 
type SSHConfig struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Port int `json:"port" yaml:"port"` // 
	PasswordAuth bool `json:"password_auth" yaml:"password_auth"` // Allow password authentication
	RootLogin bool `json:"root_login" yaml:"root_login"` // Allow root login
}




// NodeMetadata - 
type NodeMetadata struct {
	Tags []string `json:"tags" yaml:"tags"` // Semantic tags describing node capabilities
	Hardware HardwareInfo `json:"hardware" yaml:"hardware"` // 
	Hostname string `json:"hostname" yaml:"hostname"` // Canonical hostname of the node
	Purpose string `json:"purpose" yaml:"purpose"` // Primary purpose of this node
}




// HardwareInfo - 
type HardwareInfo struct {
	Model string `json:"model" yaml:"model"` // Hardware model
	CPUCores int `json:"cpu_cores" yaml:"cpu_cores"` // 
	MemoryGB int `json:"memory_gb" yaml:"memory_gb"` // 
	Architecture Architecture `json:"architecture" yaml:"architecture"` // 
}




// Architecture - 
type Architecture string

const (
	ArchitectureX8664 Architecture = "x86_64"
	ArchitectureArm64 Architecture = "arm64"
	ArchitectureArmv7 Architecture = "armv7"
)




// NodeRole - 
type NodeRole struct {
	Name RoleName `json:"name" yaml:"name"` // Semantic role identifier
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Config map[string]interface{} `json:"config" yaml:"config"` // Role-specific configuration
}




// RoleName - Semantic role identifier
type RoleName string

const (
	RoleNameVpnGateway RoleName = "vpn-gateway"
	RoleNameContainerHost RoleName = "container-host"
	RoleNameEdgeRouter RoleName = "edge-router"
	RoleNameMonitoringTarget RoleName = "monitoring-target"
	RoleNameDevWorkstation RoleName = "dev-workstation"
	RoleNameK8sNode RoleName = "k8s-node"
)




// VPNGatewayConfig - Configuration for VPN gateway role
type VPNGatewayConfig struct {
	Provider VPNProvider `json:"provider" yaml:"provider"` // 
	ServerConfig VPNServerConfig `json:"server_config" yaml:"server_config"` // 
	Routing VPNRouting `json:"routing" yaml:"routing"` // 
}




// VPNProvider - 
type VPNProvider string

const (
	VPNProviderOpenvpn VPNProvider = "openvpn"
	VPNProviderWireguard VPNProvider = "wireguard"
	VPNProviderTailscale VPNProvider = "tailscale"
)




// VPNServerConfig - 
type VPNServerConfig struct {
	Network string `json:"network" yaml:"network"` // VPN network CIDR
	Port int `json:"port" yaml:"port"` // 
	Protocol string `json:"protocol" yaml:"protocol"` // 
}




// ProtocolEnum - 
type ProtocolEnum string

const (
	ProtocolEnumUdp ProtocolEnum = "udp"
	ProtocolEnumTcp ProtocolEnum = "tcp"
)




// VPNRouting - 
type VPNRouting struct {
	IPForward bool `json:"ip_forward" yaml:"ip_forward"` // Enable IP forwarding (net.ipv4.ip_forward)
	Masquerade bool `json:"masquerade" yaml:"masquerade"` // Enable NAT masquerading for VPN clients
	Routes []VPNRoute `json:"routes" yaml:"routes"` // 
}




// VPNRoute - 
type VPNRoute struct {
	Network string `json:"network" yaml:"network"` // Destination network
	Via string `json:"via" yaml:"via"` // Gateway or interface
}




// ContainerHostConfig - Configuration for container host role
type ContainerHostConfig struct {
	Networks []ContainerNetwork `json:"networks" yaml:"networks"` // 
	Runtime ContainerRuntime `json:"runtime" yaml:"runtime"` // 
	Workloads []ContainerWorkload `json:"workloads" yaml:"workloads"` // 
}




// ContainerRuntime - 
type ContainerRuntime string

const (
	ContainerRuntimeDocker ContainerRuntime = "docker"
	ContainerRuntimeContainerd ContainerRuntime = "containerd"
	ContainerRuntimePodman ContainerRuntime = "podman"
)




// ContainerWorkload - 
type ContainerWorkload struct {
	Name string `json:"name" yaml:"name"` // Container name
	Image string `json:"image" yaml:"image"` // Container image
	State string `json:"state" yaml:"state"` // 
	Ports []PortMapping `json:"ports" yaml:"ports"` // 
	Volumes []VolumeMount `json:"volumes" yaml:"volumes"` // 
}




// StateEnum - 
type StateEnum string

const (
	StateEnumRunning StateEnum = "running"
	StateEnumStopped StateEnum = "stopped"
	StateEnumAbsent StateEnum = "absent"
)




// PortMapping - 
type PortMapping struct {
	Container int `json:"container" yaml:"container"` // 
	Protocol string `json:"protocol" yaml:"protocol"` // 
	Host int `json:"host" yaml:"host"` // 
}




// VolumeMount - 
type VolumeMount struct {
	Container string `json:"container" yaml:"container"` // 
	ReadOnly bool `json:"read_only" yaml:"read_only"` // 
	Host string `json:"host" yaml:"host"` // 
}




// ContainerNetwork - 
type ContainerNetwork struct {
	Name string `json:"name" yaml:"name"` // 
	Driver NetworkDriver `json:"driver" yaml:"driver"` // 
	Subnet string `json:"subnet" yaml:"subnet"` // Network subnet CIDR
}




// NetworkDriver - 
type NetworkDriver string

const (
	NetworkDriverBridge NetworkDriver = "bridge"
	NetworkDriverHost NetworkDriver = "host"
	NetworkDriverOverlay NetworkDriver = "overlay"
	NetworkDriverMacvlan NetworkDriver = "macvlan"
)




// NetworkTuning - Network-specific kernel parameters (semantic sysctl)
type NetworkTuning struct {
	MaxSynBacklog int `json:"max_syn_backlog" yaml:"max_syn_backlog"` // Maximum SYN backlog
	RmemMax int `json:"rmem_max" yaml:"rmem_max"` // Maximum receive buffer size
	WmemMax int `json:"wmem_max" yaml:"wmem_max"` // Maximum send buffer size
	IPForward bool `json:"ip_forward" yaml:"ip_forward"` // Enable IP forwarding (net.ipv4.ip_forward)
	BridgeNfCallIptables bool `json:"bridge_nf_call_iptables" yaml:"bridge_nf_call_iptables"` // Enable bridge netfilter (net.bridge.bridge-nf-call-iptables)
	TCPKeepaliveTime int `json:"tcp_keepalive_time" yaml:"tcp_keepalive_time"` // TCP keepalive time in seconds
}




// State - 
type State struct {
	Metadata Metadata `json:"metadata" yaml:"metadata"` // 
	Firewall FirewallConfig `json:"firewall" yaml:"firewall"` // 
	Services []ServiceConfig `json:"services" yaml:"services"` // 
	Sysctl map[string]string `json:"sysctl" yaml:"sysctl"` // 
	Packages []PackageConfig `json:"packages" yaml:"packages"` // 
	Files []FileConfig `json:"files" yaml:"files"` // 
	Version Version `json:"version" yaml:"version"` // 
}




// PackageConfig - 
type PackageConfig struct {
	Name string `json:"name" yaml:"name"` // 
	Version string `json:"version" yaml:"version"` // Desired version (empty means any)
	State PackageState `json:"state" yaml:"state"` // 
}




// PackageState - 
type PackageState string

const (
	PackageStatePresent PackageState = "present"
	PackageStateAbsent PackageState = "absent"
	PackageStateLatest PackageState = "latest"
)




// FileConfig - 
type FileConfig struct {
	Mode string `json:"mode" yaml:"mode"` // 
	Owner string `json:"owner" yaml:"owner"` // 
	Group string `json:"group" yaml:"group"` // 
	Path UnixPath `json:"path" yaml:"path"` // 
	Content string `json:"content" yaml:"content"` // Desired file content
	SHA256 string `json:"sha256" yaml:"sha256"` // Expected SHA256 hash
}




// DefaultOutgoingEnum - 
type DefaultOutgoingEnum string

const (
	DefaultOutgoingEnumAllow DefaultOutgoingEnum = "allow"
	DefaultOutgoingEnumDeny DefaultOutgoingEnum = "deny"
	DefaultOutgoingEnumReject DefaultOutgoingEnum = "reject"
)




// FirewallRule - 
type FirewallRule struct {
	Port Port `json:"port" yaml:"port"` // 
	Proto Protocol `json:"proto" yaml:"proto"` // 
	Action string `json:"action" yaml:"action"` // 
	From string `json:"from" yaml:"from"` // 
	To string `json:"to" yaml:"to"` // 
	Comment string `json:"comment" yaml:"comment"` // 
}




// ActionEnum - 
type ActionEnum string

const (
	ActionEnumAllow ActionEnum = "allow"
	ActionEnumDeny ActionEnum = "deny"
	ActionEnumReject ActionEnum = "reject"
)




// FirewallAction - 
type FirewallAction string

const (
	FirewallActionAllow FirewallAction = "allow"
	FirewallActionDeny FirewallAction = "deny"
	FirewallActionReject FirewallAction = "reject"
)




// ServiceConfig - 
type ServiceConfig struct {
	Name string `json:"name" yaml:"name"` // Service name (without .service suffix)
	State ServiceState `json:"state" yaml:"state"` // 
	Enabled bool `json:"enabled" yaml:"enabled"` // 
}




// SystemIdentity - Immutable system identifiers for node registration and validation
type SystemIdentity struct {
	CompositeKey CompositeKey `json:"composite_key" yaml:"composite_key"` // Composite identifier for database indexing
	Validation IdentityValidation `json:"validation" yaml:"validation"` // Identity validation configuration
	Registration NodeRegistration `json:"registration" yaml:"registration"` // Controller registration metadata
	Platform PlatformInfo `json:"platform" yaml:"platform"` // 
	Identifiers SystemIdentifiers `json:"identifiers" yaml:"identifiers"` // Platform-specific immutable identifiers
}




// SystemIdentifiers - Platform-specific immutable identifiers
type SystemIdentifiers struct {
	PrimaryID string `json:"primary_id" yaml:"primary_id"` // Primary system identifier (machine-id or hardware UUID)
	IDType IdentifierType `json:"id_type" yaml:"id_type"` // Type of primary identifier
	DMIBoardSerial string `json:"dmi_board_serial" yaml:"dmi_board_serial"` // Motherboard serial number
	IOPlatformUUID string `json:"io_platform_uuid" yaml:"io_platform_uuid"` // macOS IOPlatformUUID from I/O Registry
	HardwareUUID string `json:"hardware_uuid" yaml:"hardware_uuid"` // macOS Hardware UUID
	MachineID string `json:"machine_id" yaml:"machine_id"` // systemd machine-id from /etc/machine-id
	DMIProductUUID string `json:"dmi_product_uuid" yaml:"dmi_product_uuid"` // DMI/SMBIOS product UUID from /sys/class/dmi/id/product_uuid
	CollectedAt string `json:"collected_at" yaml:"collected_at"` // When these identifiers were collected
	CollectedBy string `json:"collected_by" yaml:"collected_by"` // How identifiers were collected (probe script version)
}




// IdentifierType - Type of primary identifier
type IdentifierType string

const (
	IdentifierTypeMachineId IdentifierType = "machine-id"
	IdentifierTypeHardwareUuid IdentifierType = "hardware-uuid"
	IdentifierTypeIoPlatformUuid IdentifierType = "io-platform-uuid"
	IdentifierTypeProductUuid IdentifierType = "product-uuid"
)




// CompositeKey - Composite identifier for database indexing
type CompositeKey struct {
	Key string `json:"key" yaml:"key"` // Concatenated composite key (os_type:primary_id)
	Components []KeyComponent `json:"components" yaml:"components"` // 
	Hash string `json:"hash" yaml:"hash"` // SHA256 hash of composite key for indexing
}




// KeyComponent - 
type KeyComponent struct {
	Name string `json:"name" yaml:"name"` // Component name (os_type, machine_id, etc.)
	Value string `json:"value" yaml:"value"` // Component value
}




// IdentityValidation - Identity validation configuration
type IdentityValidation struct {
	AllowOSMigration bool `json:"allow_os_migration" yaml:"allow_os_migration"` // Allow OS reinstall (machine-id changes, hardware UUID stays)
	AlertOnMismatch bool `json:"alert_on_mismatch" yaml:"alert_on_mismatch"` // Send alert if identity doesn't match
	RequireMatch bool `json:"require_match" yaml:"require_match"` // Fail if identity doesn't match config
	CheckOnStartup bool `json:"check_on_startup" yaml:"check_on_startup"` // Validate identity when exporter starts
}




// NodeRegistration - Controller registration metadata
type NodeRegistration struct {
	RegistrationToken string `json:"registration_token" yaml:"registration_token"` // Token for initial registration (rotated after first use)
	LastCheckin string `json:"last_checkin" yaml:"last_checkin"` // 
	Registered bool `json:"registered" yaml:"registered"` // Whether node is registered with controller
	RegisteredAt string `json:"registered_at" yaml:"registered_at"` // 
	ControllerURL string `json:"controller_url" yaml:"controller_url"` // URL of controlling instance
}




// PlatformInfo - 
type PlatformInfo struct {
	OSType OSType `json:"os_type" yaml:"os_type"` // Operating system type
	OSFamily OSFamily `json:"os_family" yaml:"os_family"` // OS distribution family
	OSVersion string `json:"os_version" yaml:"os_version"` // OS version string
	KernelVersion string `json:"kernel_version" yaml:"kernel_version"` // Kernel version
}




// OSType - Operating system type
type OSType string

const (
	OSTypeLinux OSType = "linux"
	OSTypeDarwin OSType = "darwin"
	OSTypeWindows OSType = "windows"
	OSTypeBsd OSType = "bsd"
)




// OSFamily - OS distribution family
type OSFamily string

const (
	OSFamilyDebian OSFamily = "debian"
	OSFamilyRhel OSFamily = "rhel"
	OSFamilyArch OSFamily = "arch"
	OSFamilyAlpine OSFamily = "alpine"
	OSFamilyMacos OSFamily = "macos"
	OSFamilyWindows OSFamily = "windows"
)




// WatcherConfig - 
type WatcherConfig struct {
	Version Version `json:"version" yaml:"version"` // 
	Watchers Watchers `json:"watchers" yaml:"watchers"` // 
	EventHandler EventHandler `json:"event_handler" yaml:"event_handler"` // Configuration for event processing
}




// Watchers - 
type Watchers struct {
	Journald JournaldWatcher `json:"journald" yaml:"journald"` // 
	Auditd AuditdWatcher `json:"auditd" yaml:"auditd"` // 
	Dbus DBusWatcher `json:"dbus" yaml:"dbus"` // 
	Enabled bool `json:"enabled" yaml:"enabled"` // Master switch for all watchers
	Inotify InotifyWatcher `json:"inotify" yaml:"inotify"` // 
}




// JournaldWatcher - 
type JournaldWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Units []ServiceUnit `json:"units" yaml:"units"` // Systemd units to monitor logs
}




// AuditdWatcher - 
type AuditdWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Commands []Command `json:"commands" yaml:"commands"` // Commands to audit for execution
	Syscalls []string `json:"syscalls" yaml:"syscalls"` // Syscalls to monitor (e.g., execve, open, connect)
}




// DBusWatcher - 
type DBusWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Signals []string `json:"signals" yaml:"signals"` // D-Bus signals to monitor
}




// InotifyWatcher - 
type InotifyWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Paths []UnixPath `json:"paths" yaml:"paths"` // File paths to monitor for changes
}




// EventHandler - Configuration for event processing
type EventHandler struct {
	BufferSize int `json:"buffer_size" yaml:"buffer_size"` // Event channel buffer size
	DebounceMs int `json:"debounce_ms" yaml:"debounce_ms"` // Milliseconds to debounce rapid events
	BatchSize int `json:"batch_size" yaml:"batch_size"` // Max events to batch before processing
}




// LoadStateConfig loads state configuration from YAML file
func LoadStateConfig(path string) (*State, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var config State
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse yaml: %w", err)
	}

	return &config, nil
}

// LoadWatcherConfig loads watcher configuration from YAML file
func LoadWatcherConfig(path string) (*WatcherConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var config WatcherConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse yaml: %w", err)
	}

	return &config, nil
}
