// Code generated by schema generator. DO NOT EDIT.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)



// ServiceUnit - Systemd unit name
type ServiceUnit string




// Version - Schema version in MAJOR.MINOR format
type Version string




// Metadata - 
type Metadata struct {
	Site string `json:"site" yaml:"site"` // Unique site identifier (typically hostname)
	Environment string `json:"environment" yaml:"environment"` // 
	Description string `json:"description" yaml:"description"` // 
	Labels map[string]interface{} `json:"labels" yaml:"labels"` // 
	Annotations map[string]interface{} `json:"annotations" yaml:"annotations"` // 
}




// EnvironmentEnum - 
type EnvironmentEnum string

const (
	EnvironmentEnumProduction EnvironmentEnum = "production"
	EnvironmentEnumStaging EnvironmentEnum = "staging"
	EnvironmentEnumDevelopment EnvironmentEnum = "development"
	EnvironmentEnumHomeLab EnvironmentEnum = "home-lab"
)




// Port - Valid TCP/UDP port number
type Port int




// Protocol - Network protocol
type Protocol string

const (
	ProtocolTcp Protocol = "tcp"
	ProtocolUdp Protocol = "udp"
	ProtocolIcmp Protocol = "icmp"
)




// ServiceState - Systemd service state
type ServiceState string

const (
	ServiceStateRunning ServiceState = "running"
	ServiceStateStopped ServiceState = "stopped"
	ServiceStateDisabled ServiceState = "disabled"
)




// UnixPath - Absolute Unix filesystem path
type UnixPath string




// Command - Shell command or binary name
type Command string




// State - 
type State struct {
	Sysctl map[string]string `json:"sysctl" yaml:"sysctl"` // 
	Packages []PackageConfig `json:"packages" yaml:"packages"` // 
	Files []FileConfig `json:"files" yaml:"files"` // 
	Version Version `json:"version" yaml:"version"` // 
	Metadata Metadata `json:"metadata" yaml:"metadata"` // 
	Firewall FirewallConfig `json:"firewall" yaml:"firewall"` // 
	Services []ServiceConfig `json:"services" yaml:"services"` // 
}




// FirewallConfig - 
type FirewallConfig struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	DefaultIncoming FirewallAction `json:"default_incoming" yaml:"default_incoming"` // 
	DefaultOutgoing string `json:"default_outgoing" yaml:"default_outgoing"` // 
	Rules []FirewallRule `json:"rules" yaml:"rules"` // 
}




// FirewallAction - 
type FirewallAction string

const (
	FirewallActionAllow FirewallAction = "allow"
	FirewallActionDeny FirewallAction = "deny"
	FirewallActionReject FirewallAction = "reject"
)




// DefaultOutgoingEnum - 
type DefaultOutgoingEnum string

const (
	DefaultOutgoingEnumAllow DefaultOutgoingEnum = "allow"
	DefaultOutgoingEnumDeny DefaultOutgoingEnum = "deny"
	DefaultOutgoingEnumReject DefaultOutgoingEnum = "reject"
)




// FirewallRule - 
type FirewallRule struct {
	Port Port `json:"port" yaml:"port"` // 
	Proto Protocol `json:"proto" yaml:"proto"` // 
	Action string `json:"action" yaml:"action"` // 
	From string `json:"from" yaml:"from"` // 
	To string `json:"to" yaml:"to"` // 
	Comment string `json:"comment" yaml:"comment"` // 
}




// ActionEnum - 
type ActionEnum string

const (
	ActionEnumAllow ActionEnum = "allow"
	ActionEnumDeny ActionEnum = "deny"
	ActionEnumReject ActionEnum = "reject"
)




// ServiceConfig - 
type ServiceConfig struct {
	State ServiceState `json:"state" yaml:"state"` // 
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Name string `json:"name" yaml:"name"` // Service name (without .service suffix)
}




// PackageConfig - 
type PackageConfig struct {
	Name string `json:"name" yaml:"name"` // 
	Version string `json:"version" yaml:"version"` // Desired version (empty means any)
	State PackageState `json:"state" yaml:"state"` // 
}




// PackageState - 
type PackageState string

const (
	PackageStatePresent PackageState = "present"
	PackageStateAbsent PackageState = "absent"
	PackageStateLatest PackageState = "latest"
)




// FileConfig - 
type FileConfig struct {
	Content string `json:"content" yaml:"content"` // Desired file content
	SHA256 string `json:"sha256" yaml:"sha256"` // Expected SHA256 hash
	Mode string `json:"mode" yaml:"mode"` // 
	Owner string `json:"owner" yaml:"owner"` // 
	Group string `json:"group" yaml:"group"` // 
	Path UnixPath `json:"path" yaml:"path"` // 
}




// WatcherConfig - 
type WatcherConfig struct {
	EventHandler EventHandler `json:"event_handler" yaml:"event_handler"` // Configuration for event processing
	Version Version `json:"version" yaml:"version"` // 
	Watchers Watchers `json:"watchers" yaml:"watchers"` // 
}




// Watchers - 
type Watchers struct {
	Journald JournaldWatcher `json:"journald" yaml:"journald"` // 
	Auditd AuditdWatcher `json:"auditd" yaml:"auditd"` // 
	Dbus DBusWatcher `json:"dbus" yaml:"dbus"` // 
	Enabled bool `json:"enabled" yaml:"enabled"` // Master switch for all watchers
	Inotify InotifyWatcher `json:"inotify" yaml:"inotify"` // 
}




// InotifyWatcher - 
type InotifyWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Paths []UnixPath `json:"paths" yaml:"paths"` // File paths to monitor for changes
}




// JournaldWatcher - 
type JournaldWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Units []ServiceUnit `json:"units" yaml:"units"` // Systemd units to monitor logs
}




// AuditdWatcher - 
type AuditdWatcher struct {
	Syscalls []string `json:"syscalls" yaml:"syscalls"` // Syscalls to monitor (e.g., execve, open, connect)
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Commands []Command `json:"commands" yaml:"commands"` // Commands to audit for execution
}




// DBusWatcher - 
type DBusWatcher struct {
	Enabled bool `json:"enabled" yaml:"enabled"` // 
	Signals []string `json:"signals" yaml:"signals"` // D-Bus signals to monitor
}




// EventHandler - Configuration for event processing
type EventHandler struct {
	BufferSize int `json:"buffer_size" yaml:"buffer_size"` // Event channel buffer size
	DebounceMs int `json:"debounce_ms" yaml:"debounce_ms"` // Milliseconds to debounce rapid events
	BatchSize int `json:"batch_size" yaml:"batch_size"` // Max events to batch before processing
}




// LoadStateConfig loads state configuration from YAML file
func LoadStateConfig(path string) (*State, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var config State
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse yaml: %w", err)
	}

	return &config, nil
}

// LoadWatcherConfig loads watcher configuration from YAML file
func LoadWatcherConfig(path string) (*WatcherConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var config WatcherConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("parse yaml: %w", err)
	}

	return &config, nil
}
